[#1] 멀티 모듈 구조 작업
f-lab-edu/beautify-project pull request #2
Opened 2024-11-12 03:28 UTC by sssukho

멀티 모듈 구조 작업 중 아래와 같이 빌드가 되지 않는 이슈가 있습니다.

![스크린샷 2024-11-12 오후 12 25 47](https://github.com/user-attachments/assets/616833d2-57a8-4f67-8fb7-7f115635a082)

위 슬랙 내용중 빌드가 되지 않는 모듈은(a 모듈) `bp-app-batch` 입니다.

2024-11-13 04:09 UTC, f-lab-lyan requested changes
.gradle, .idea를 .gitignore에 추가해주시고, 이 PR에서도 삭제해주세요. :-)

2024-11-13 04:22 UTC, f-lab-lyan commented
방금 확인했는데요. 모든 서브 모듈에 gradlew랑 settings.gradle이 존재하네요. 이 부분을 지우시면 될 것 같습니다. 그리고 이 부분이 어떤 역할을 하는지 고민해 보시면 좋을 것 같네요. :-)

2024-11-13 12:14 UTC, sssukho commented
[우아한 기술블로그 - 멀티모듈 설계 이야기 with Spring, Gradle](https://techblog.woowahan.com/2637/) 을 참고하여 아래와 같이 구성해보았습니다.

1. 독립 모듈 계층: 시스템과 무관한 모듈로, 다른 모듈들을 의존(import)할 수 없다.
   - 없음

2. 공통 모듈 계층: 모든 모듈에서 사용될 수 있는 모듈로, 다른 모듈들을 의존할 수 없다.
   - `bp-dto` : DTO를 가지는 역할을 한다.
   - `bp-utils` : Util 클래스만 가지는 역할을 한다.
   
3. 도메인 모듈 계층: 도메인 모듈, 독립 모듈, 공통 모듈을 의존할 수 있다.
   - 최대 하나의 인프라(저장소)에 대한 책임만 갖고, 도메인 비즈니스만 수행하는 역할을 갖는다.
   - `bp-domain-rdb`: rdb 설정 코드, repository, domain service, domain 등의 클래스를 갖는다.
   
4. 내부 모듈 계층: 내부 모듈, 독립 모듈, 공통 모듈을 의존할 수 있다.
   - `bp-kafka-event-publisher`: kafka에 이벤트를 publish 하기 위한 모듈
   - `bp-core-web`: 웹 설정을 가지고 있는 모듈 (WebFilter 등등 을 가지고 있음)
   
5. 애플리케이션 모듈 계층
   - 가장 상위 계층으로, 하위 계층들을 조립하여 서비스 비즈니스를 완성한다.
   - `bp-app-api`: client 에서 호출할 때 수행해야 할 실제 비즈니스 로직을 가지고 있는 모듈 
   - `bp-app-batch`: 배치성 비즈니스 로직을 가지고 있는 모듈

2024-11-14 01:09 UTC, f-lab-lyan commented on settings.gradle
> +include ':bp-app-api', ':bp-app-batch', ':bp-core-web', ':bp-dto', ':bp-dto',
```suggestion
include 'bp-app-api', 'bp-app-batch', 'bp-core-web', ':bp-dto', ':bp-dto',
```

2024-11-14 01:16 UTC, f-lab-lyan commented on .gitignore
필요없는 내용은 일단 빼면 좋을 것 같습니다.

2024-11-14 01:24 UTC, f-lab-lyan commented on settings.gradle
> +        ':bp-kafka-event-publisher', ':bp-utils', ':bp-domain-rdb'
<img width="99" alt="image" src="https://github.com/user-attachments/assets/1634996f-b2db-4c62-8117-31e35a1b2989">

2024-11-14 01:48 UTC, f-lab-lyan commented on build.gradle
> +	id 'org.springframework.boot' version '3.3.5'
```suggestion
	id 'org.springframework.boot' version '3.3.5' apply false
```

2024-11-15 15:17 UTC, sssukho commented
6주차 멘토링(2024-11-14)에서 말씀해주신 내용 모두 반영하였습니다! 😅

2024-11-18 04:46 UTC, f-lab-lyan approved these changes

2024-11-18 04:46 UTC, f-lab-lyan commented
고생하셨습니다. :-) 편하실 때, 머지 하시죠!

2024-11-18 10:31 UTC, merged